version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgres://myuser:mypassword@db:5432/mydb"
  #   depends_on:
  #     - db
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://localhost:3000"
  #   depends_on:
  #     - backend
